# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Master branch build & broski

on:
  pull_request:
    branches: [ "master" ]
    types: [opened]

permissions:
  contents: read

jobs:
  master-build-and-test:
    env:
      DISPLAY: :0
      TNB_EMAIL: ${{ secrets.TNB_EMAIL }}
      TNB_PASSWORD: ${{ secrets.TNB_PASSWORD }}
      AIR_EMAIL: ${{ secrets.AIR_EMAIL }}
      AIR_PASSWORD: ${{ secrets.AIR_PASSWORD }}
      mynum: ${{ secrets.mynum }}
      ws_group_id: ${{ secrets.ws_group_id }}

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Allow permissions to execute shell scripts
        run: sudo chmod +x setup.sh runner.sh
        shell: sh

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v1

      - name: Set up terminal dependencies.
        run: ./setup.sh
        shell: sh

      - name: xhost setup
        run: xhost +si:localuser:runner
        shell: sh

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
