# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Master branch main cron job

on:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: read

jobs:
  master-cron-execution:
    env:
      DISPLAY: :0
      TNB_EMAIL: ${{ secrets.TNB_EMAIL }}
      TNB_PASSWORD: ${{ secrets.TNB_PASSWORD }}
      AIR_EMAIL: ${{ secrets.AIR_EMAIL }}
      AIR_PASSWORD: ${{ secrets.AIR_PASSWORD }}
      mynum: ${{ secrets.mynum }}
      ws_api_url: ${{ secrets.ws_api_url }}
      ws_api_id: ${{ secrets.ws_api_id }}
      DB_URI: ${{ secrets.DB_URI }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Allow permissions to execute shell scripts
        run: sudo chmod +x setup.sh runner.sh
        shell: sh

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v1

      - name: Set up terminal dependencies.
        run: ./setup.sh
        shell: sh

      - name: xhost setup
        run: xhost +si:localuser:runner
        shell: sh

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Venv activation
        run: . venv/bin/activate
        shell: sh

      - name: Reinstall pip libraries
        run: pip install -r requirements.txt
        shell: sh

      - name: Run app
        run: python3 main.py --send_message -db billing
