# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Bill splitter github actions pipeline

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        TNB_EMAIL: ${{ secrets.TNB_EMAIL }}
        TNB_PASSWORD: ${{ secrets.TNB_PASSWORD }}
        AIR_EMAIL: ${{ secrets.AIR_EMAIL }}
        AIR_PASSWORD: ${{ secrets.AIR_PASSWORD }}
        mynum: ${{ secrets.mynum }}
        ws_group_id: ${{ secrets.ws_group_id }}
    - name: Allow permissions to execute shell scripts
      run: sudo chmod +x setup.sh runner.sh
      shell: sh
    - name: Set up terminal dependencies.
      run: ./setup.sh
      shell: sh
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: check display
      run: echo $DISPLAY
      shell: sh
    - name: Venv activation
      run: . venv/bin/activate
      shell: sh
    - name: Reinstall pip libraries
      run: pip install -r requirements.txt
      shell: sh
    - name: Add DISPLAY env variable
      run: export DISPLAY=:0
      shell: sh
    - name: check display
      run: echo $DISPLAY
      shell: sh
    - name: Run python app (main.py)
      run: python3 main.py
      shell: sh
    - name: check display
      run: echo $DISPLAY
      shell: sh
    - name: Venv deactivation
      run: deactivate
      shell: sh
